# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <.m_axis>
  # <.pcs_gt>
  ".appdef",
  # <.m_axis>
  # <.pcs_gt>
  ".includes",
  # <.m_axis>
  "app_def",
  # <.m_axis>
  # <.pcs_gt>
  "ax4",
  # <.m_axis>
  # <.pcs_gt>
  "ax5",
  # <tables>
  # <.operation>
  # <.part>
  "axis",
  # <.pcs_gt>
  "bottom_col_names",
  # <.m_axis>
  "bottom_inc",
  # <code_range>
  # <.inc_part>
  # <tables>
  # <.part>
  "code",
  # <.operation>
  "code_2",
  # <.operation>
  "code_3",
  # <.inc_part>
  # <.part>
  "code_4",
  # <definitions>
  # <.def_op>
  # <.def_ap>
  "definition",
  # <.def_op>
  "display",
  # <definitions>
  # <.def_op>
  "explanation",
  # <definitions>
  # <.def_op>
  # <.inc_part>
  # <.def_ap>
  # <tables>
  "label",
  # <tables>
  "label_2",
  # <tables>
  # <.operation>
  "label_3",
  # <.inc_part>
  # <.part>
  "label_4",
  # <index>
  "letter",
  # <tables>
  "name",
  # <tables>
  "name_1",
  # <tables>
  # <.operation>
  "name_3",
  # <tables>
  # <.operation>
  # <.part>
  "name_4",
  # <tables>
  # <.part>
  "rowid",
  # <index>
  "subterm",
  # <index>
  "term",
  # <index>
  "term_id",
  # <.pcs_gt>
  "top",
  # <.part>
  "value",
  # <index>
  "verb",
  NULL
))
