# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <.m_axis>
  # <.pcs_gt>
  ".appdef",
  # <.m_axis>
  # <.pcs_gt>
  ".includes",
  # <.m_axis>
  "app_def",
  # <.m_axis>
  # <.pcs_gt>
  "ax4",
  # <.m_axis>
  # <.pcs_gt>
  "ax5",
  # <gt_pcs>
  # <gt_pcs2>
  # <tables>
  # <.operation>
  # <.part>
  "axis",
  # <.pcs_gt>
  "bottom_col_names",
  # <.m_axis>
  "bottom_inc",
  # <code_range>
  # <.inc_part>
  # <tables>
  # <.part>
  # <.pcs_part>
  "code",
  # <.operation>
  # <.pcs_operation>
  "code_2",
  # <.operation>
  # <.pcs_operation>
  "code_3",
  # <.inc_part>
  # <.part>
  # <.pcs_part>
  "code_4",
  # <definitions>
  # <.def_op>
  # <.def_ap>
  "definition",
  # <.def_op>
  "display",
  # <definitions>
  # <.def_op>
  "explanation",
  # <definitions>
  # <gt_pcs>
  # <.def_op>
  # <.inc_part>
  # <.def_ap>
  # <tables>
  "label",
  # <tables>
  "label_2",
  # <tables>
  # <.operation>
  # <.pcs_operation>
  "label_3",
  # <.inc_part>
  # <.part>
  # <.pcs_part>
  "label_4",
  # <index>
  "letter",
  # <tables>
  "name",
  # <tables>
  "name_1",
  # <tables>
  # <.operation>
  # <.pcs_operation>
  "name_3",
  # <tables>
  # <.operation>
  # <.part>
  # <.pcs_operation>
  # <.pcs_part>
  "name_4",
  # <tables>
  # <.part>
  # <.pcs_part>
  # <.pcs_approach>
  # <.pcs_device>
  # <.pcs_qualifier>
  "rowid",
  # <index>
  "subterm",
  # <index>
  "term",
  # <index>
  "term_id",
  # <.pcs_gt>
  "top",
  # <gt_pcs>
  # <gt_pcs2>
  # <.pcs_section>
  # <.pcs_system>
  # <.pcs_operation>
  # <.pcs_part>
  # <.pcs_approach>
  # <.pcs_device>
  # <.pcs_qualifier>
  "value",
  NULL
))
