# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <code_range>
  "code",
  # <definitions>
  "definition",
  # <definitions>
  "explanation",
  # <definitions>
  "label",
  # <index>
  "letter",
  # <index>
  "subterm",
  # <index>
  "term",
  # <index>
  "term_id",
  # <index>
  "verb",
  NULL
))
